<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2576" started-at="2015-10-22T04:18:31Z" finished-at="2015-10-22T04:18:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2576" started-at="2015-10-22T04:18:31Z" finished-at="2015-10-22T04:18:33Z">
      <class name="com.shipwire.tests.Shipwire_RestServicesTests.RestServiceTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.shipwire.tests.Shipwire_RestServicesTests.RestServiceTest@62715cb7]" name="setup" is-config="true" duration-ms="280" started-at="2015-10-21T21:18:31Z" finished-at="2015-10-21T21:18:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="createOrder(java.lang.String, java.lang.String, java.lang.String, java.lang.String, int, java.lang.String)[pri:0, instance:com.shipwire.tests.Shipwire_RestServicesTests.RestServiceTest@62715cb7]" name="createOrder" duration-ms="2282" started-at="2015-10-21T21:18:31Z" data-provider="CreateOrderData" finished-at="2015-10-21T21:18:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Create order API with correct login credentials]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[shalinig123@yahoo.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[held]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order status returned from response is incorrect. Actual: [] -- Expected: held expected [held] but found [[]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order status returned from response is incorrect. Actual: [] -- Expected: held expected [held] but found [[]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.shipwire.tests.Shipwire_RestServicesTests.RestServiceTest.createOrder(RestServiceTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrder -->
      </class> <!-- com.shipwire.tests.Shipwire_RestServicesTests.RestServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
